import { Prototype } from '../../launcher/src/prototypes'

export const rhdhPrototypes: Prototype[] = [
  {
    name: 'Lightspeed for RHDH',
    project: 'AI-Powered Developer Assistant',
    product: 'RHDH',
    description: 'An AI-powered assistant integrated into Red Hat Developer Hub, enabling developers to interact with Lightspeed capabilities directly within their development workflow. Provides intelligent code suggestions, documentation lookups, and guided troubleshooting.',
    externalUrl: 'https://lightspeed-plugin-477a0f.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Observability for Entities',
    project: 'Entity Health & Performance Monitoring',
    product: 'RHDH',
    description: 'Catalog improvements that bring observability data directly into entity views, giving developers quick visibility into the health and performance of their services without leaving Developer Hub.',
    externalUrl: 'https://catalog-improvements-4155c7.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'RBAC for RHDH',
    project: 'Role-Based Access Control Management',
    product: 'RHDH',
    description: 'Role-based access control management for Red Hat Developer Hub, allowing administrators to define roles, assign permissions, and control access to resources across the platform.',
    externalUrl: 'https://rbac-2c1057.pages.redhat.com',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Guided Tour',
    project: 'Interactive Onboarding Experience',
    product: 'RHDH',
    description: 'An interactive guided tour experience for Red Hat Developer Hub, helping new members onboard quickly by walking them through key features, navigation, and workflows step by step.',
    externalUrl: 'https://backstage-with-rhdh-theme-3f4a21.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'RHDH Home Page',
    project: 'Personalized Developer Landing Page',
    product: 'RHDH',
    description: 'A redesigned home page for Red Hat Developer Hub, providing a personalized landing experience with quick access to recent entities, starred items, and platform-wide announcements.',
    externalUrl: 'https://homepage-ebd5ce.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Orchestrator',
    project: 'Workflow Exploration',
    product: 'RHDH',
    description: 'A workflow orchestration component for Red Hat Developer Hub, enabling teams to design, execute, and monitor automated workflows directly from the platform.',
    externalUrl: 'https://orchestrator-191ef6.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Scorecards',
    project: 'Software Quality & Compliance Tracking',
    product: 'RHDH',
    description: 'A scorecards system for Red Hat Developer Hub that tracks and visualizes software quality, compliance, and best-practice adoption across catalog entities.',
    externalUrl: 'https://scorecards-1152db.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Learning Paths',
    project: 'Developer Education & Skill Building',
    product: 'RHDH',
    description: 'A learning paths plugin for Red Hat Developer Hub, offering curated educational content and step-by-step guides to help developers grow their skills within the platform.',
    externalUrl: 'https://learning-paths-55d6a1.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'DCM',
    project: 'Data Center Management',
    product: 'RHDH',
    description: 'A data center management prototype for Red Hat Developer Hub, providing visibility into data center infrastructure, resource allocation, and operational status directly within the platform.',
    externalUrl: 'https://dcm-4dc8dc.pages.redhat.com',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Skill Marketplace',
    project: 'Agentic Skill Discovery & Sharing',
    product: 'RHDH',
    description: 'A marketplace for discovering, sharing, and managing reusable skills and agents within Red Hat Developer Hub, enabling teams to leverage AI-powered automation across their development workflows.',
    externalUrl: 'https://agentic-524bde.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'May 6, 2026',
  },
  {
    name: 'Gamification',
    project: 'Badge Management & Leaderboard System',
    product: 'RHDH',
    description: 'A gamification system for Red Hat Developer Hub that lets administrators create and manage badges, assign them to members based on platform activity, and display leaderboards to encourage engagement and recognize contributions.',
    externalUrl: 'https://backstage-scorecards-b86fc7.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'May 20, 2026',
  },
  {
    name: 'Conversion Hub',
    project: 'Chef-to-Ansible Migration Tool',
    product: 'RHDH',
    description: 'A conversion hub for Red Hat Developer Hub that enables teams to initiate and track the asynchronous conversion of Chef cookbooks into production-ready Ansible Playbooks, with detailed status tracking and plan review workflows.',
    externalUrl: 'https://migration-hub-c63a3f.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'May 20, 2026',
  },
  {
    name: 'Overview Page Improvements',
    project: 'Catalog & Entity Overview UX',
    product: 'RHDH',
    description:
      'Catalog and entity overview improvements for Red Hat Developer Hub, including integration health in the catalog table, dashboard tiles linked to entity tabs, template run metrics, and a GitLab Pages demo of the updated experience.',
    externalUrl: 'https://overview-page-improvements-6424e0.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Jun 15, 2026',
  },
  {
    name: 'Template Management',
    project: 'Software Template Governance',
    product: 'RHDH',
    description:
      'Administration experience for managing software templates in Red Hat Developer Hub: searchable template table with metrics and catalog actions, per-template Usage and Execution output views, scaffolder create flows, and Build with AI for orchestrator-style template authoring with chat history and registration status.',
    externalUrl: 'https://template-management-e4f367.pages.redhat.com/administration/template-management',
    path: '',
    status: 'Active',
    lastUpdated: 'Jul 2, 2026',
  },
  {
    name: 'Layout Management',
    project: 'Administration Layout & Navigation',
    product: 'RHDH',
    description:
      'Administration experience for customizing RHDH navigation and global header layout: reorder sidebar and header items, pin items to the bottom, add or remove nav entries, insert border dividers, and preview changes in the live sidebar with RHDH scope and in-memory static catalog on GitLab Pages.',
    externalUrl:
      'https://layout-plugin-e9a6ff.pages.redhat.com/administration/layout?scope=rhdh',
    path: '',
    status: 'Active',
    lastUpdated: 'Jul 2, 2026',
  },
  {
    name: 'Extensions',
    project: 'Marketplace Extensions Plugin',
    product: 'RHDH',
    description:
      'RHDH Extensions (marketplace) experience for discovering, installing, enabling, disabling, and configuring plugins. Includes the Extensions catalog and installed packages views, plugin detail drawer with actions, YAML configuration edit flow, and RHDH Theme / Backstage BUI prototype scopes on GitLab Pages.',
    externalUrl: 'https://extensions-e74028.pages.redhat.com/',
    buttonLabel: 'Launch prototype (VPN required)',
    path: '',
    status: 'Active',
    lastUpdated: 'Aug 6, 2026',
  },
  {
    name: 'RHDH Theme',
    project: 'RHDH Platform Shell & Theme',
    product: 'RHDH',
    description:
      'The main RHDH prototype base on Backstage 1.52 with BUI shell, RHDH branding, and a release-scoped theme view. Includes the prototype scope switcher, global header, PatternFly-style page inset, in-memory static catalog for GitLab Pages, and the shared fork starting point at uxd/prototypes/backstage.',
    externalUrl: 'https://backstage-7587c0.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Jun 23, 2026',
  },
  {
    name: 'RHDH Designer Onboarding',
    project: 'Cursor & Claude Code Agent Skills',
    product: 'RHDH',
    description:
      'Standalone agent skill for Cursor and Claude Code for new RHDH designers: Day 1 setup through first published GitLab Pages prototype. Includes environment checklist, workflow decision tree, Week 1 path, mock data playbook, and pre-publish verification.',
    externalUrl: 'https://gitlab.cee.redhat.com/shirshbe/skill-rhdh-designer-onboarding',
    buttonLabel: 'View skill (VPN required)',
    path: '',
    tags: [{ label: 'AI skill', color: 'yellow', icon: 'stars' }],
    status: 'Active',
    lastUpdated: 'Jun 23, 2026',
  },
  {
    name: 'RHDH UX Designer',
    project: 'Cursor & Claude Code Agent Skills',
    product: 'RHDH',
    description:
      'Agent skill for Cursor and Claude Code for RHDH UI standards: Backstage UI (BUI), RHDH theme and global header, GitLab Pages baseline, prototype scope switcher placement, design review checklist, and Jira workflow guidance.',
    externalUrl: 'https://gitlab.cee.redhat.com/shirshbe/skill-rhdh-ux-designer',
    buttonLabel: 'View skill (VPN required)',
    path: '',
    tags: [{ label: 'AI skill', color: 'yellow', icon: 'stars' }],
    status: 'Active',
    lastUpdated: 'Jun 23, 2026',
  },
  {
    name: 'RHDH Prototype Handoff',
    project: 'Cursor & Claude Code Agent Skills',
    product: 'RHDH',
    description:
      'Agent skill for Cursor and Claude Code with a reusable PrototypeViewSwitcher component for multi-release RHDH prototypes. Covers release-scoped views, RELEASE-MAPPING, engineering handoff artifacts, and canonical scope bar placement.',
    externalUrl: 'https://gitlab.cee.redhat.com/shirshbe/skill-rhdh-prototype-handoff',
    buttonLabel: 'View skill (VPN required)',
    path: '',
    tags: [{ label: 'AI skill', color: 'yellow', icon: 'stars' }],
    status: 'Active',
    lastUpdated: 'Jun 23, 2026',
  },
  {
    name: 'Enterprise Skills Server',
    project: 'Agent Skills Directory',
    product: 'RHDH',
    description:
      'A skills directory for discovering, installing and managing agent skills. Includes a searchable skills catalog, skill detail pages, and an admin UI for registering sources and managing skills.',
    externalUrl: 'https://rhess-7078a2.pages.redhat.com/skills',
    buttonLabel: 'Launch prototype (VPN required)',
    path: '',
    status: 'Active',
    lastUpdated: 'Jun 29, 2026',
  },
]
