import { Prototype } from '../../launcher/src/prototypes'

export const podmanDesktopPrototypes: Prototype[] = [
  {
    name: 'Enterprise Support Page',
    project: 'Enterprise Support Page',
    product: 'Podman Desktop',
    description: 'A prototype for a new "Get Started" page on podman-desktop.io that presents both the community path (downloads, docs, tutorials) and enterprise support vendors (Red Hat Desktop) in a two-column layout. Includes a prototype toggle bar to preview how the page scales from 1 vendor to many vendors, following CNCF website guidelines.',
    externalUrl: 'https://enterprise-support-cd3849.pages.redhat.com/get-started',
    path: '',
    status: 'In Progress',
    lastUpdated: 'Jul 21, 2026',
  },
  {
    name: 'Podman Desktop PF Alignment',
    project: 'PatternFly Component Alignment',
    product: 'Podman Desktop',
    description: 'A prototype exploring the alignment of Podman Desktop UI components with PatternFly design patterns, ensuring visual and behavioral consistency with the Red Hat design system.',
    externalUrl: 'https://storybook-102f60.pages.redhat.com/',
    path: '',
    status: 'Active',
    lastUpdated: 'Apr 30, 2026',
  },
  {
    name: 'Volume Export / Import',
    project: 'Volume Backup & Restore',
    product: 'Podman Desktop',
    description: 'A prototype demonstrating volume export and import flows for Podman Desktop, allowing users to back up volume data to a tar archive and restore volumes from an archive file.',
    externalUrl: 'https://github.com/podman-desktop/podman-desktop/pull/17739',
    buttonLabel: 'View PR',
    path: '',
    status: 'In Progress',
    lastUpdated: 'May 27, 2026',
  },
  {
    name: 'Kubernetes Developer Sandbox',
    project: 'Kubernetes Developer Sandbox Promotion',
    product: 'Podman Desktop',
    description: 'A prototype adding a Red Hat Developer Sandbox prompt to the Kubernetes page in Podman Desktop. When users have no active cluster, they see a recommended card encouraging sign-up for Developer Sandbox, providing an easy path to a managed Kubernetes environment with Install/Connect actions.',
    externalUrl: 'https://github.com/podman-desktop/podman-desktop/pull/17775',
    buttonLabel: 'View PR',
    path: '',
    status: 'In Progress',
    lastUpdated: 'Jun 8, 2026',
  },
  {
    name: 'Extensions UX Redesign',
    project: 'Extension Updates and Catalog Improvements',
    product: 'Podman Desktop',
    description: 'A prototype proposing a comprehensive redesign of the Extensions section: the Installed tab, Catalog tab, and extension details page. Introduces a sortable table view, sticky filter toolbar, unified kebab menu, richer lifecycle status indicators, a grid/list view toggle for the Catalog, and a Change version modal — making extension management clearer, more discoverable, and more actionable.',
    externalUrl: 'https://github.com/podman-desktop/podman-desktop/pull/18297',
    buttonLabel: 'View PR',
    path: '',
    status: 'In Progress',
    lastUpdated: 'Jul 15, 2026',
  },
]
